---
name: CI
'on':
  push:
    paths:
      - '**.sh'
      - '**.yml'
      - '**.yaml'
      - '**.c'
      - '**.h'
      - '**Makefile'
      - '**.csproj'
      - '**.sln'
  pull_request: {}
  workflow_dispatch: {}
jobs:
 shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'workflow_dispatch' }}
    steps:
      - uses: actions/checkout@v4
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        env:
          SHELLCHECK_OPTS: -x
        with:
          check_together: true
        continue-on-error: true
 lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint Codebase
        uses: github/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: '${GITHUB_TOKEN}'
